name: Server builds

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Cache .gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          # Enable concurrent cache save and restore
          # Default is concurrent=false for better log readability
          concurrent: true
          # Disable caching of $HOME/.gradle/caches/*.*/generated-gradle-jars
          save-generated-gradle-jars: false
          # Disable publishing Gradle Build Scan URL to job report
          gradle-build-scan-report: false
      - name: Delete old jar's
        run: rm -f */*/build/libs/*.jar
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup Ketting, Check Setup Ketting & Generate KettingJar
        run: ./gradlew build
      - name: tar build dir
        run: |
          tar -czf build.tar.gz build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-dir
          path: |
            build.tar.gz
